version: "3"
services:
  go:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: go_container
    tty: true
    volumes:
      - "./server:/usr/src/app/server"
    command: ./main
    ports:
      - "8080:8080"
    depends_on:
      - "db"
      - "redis"
    env_file:
      - dev.env
  db:
    image: mysql:8.0
    container_name: mysql_container
    volumes:
      - db-store:/var/lib/mysql
      - ./DB/logs:/var/log/mysql
      - ./DB/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - dev.env
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  redis:
    image: "redis:6.0-alpine"
    container_name: redis_container
    volumes:
      - "./DB/redis:/redis"
    ports:
      - "6379:6379"
volumes:
  db-store:
