version: "3"
services:
  go:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: go_container
    tty: true
    volumes:
      - "./server:/usr/src/app/server"
    command: go run cmd/index-indicators/main.go
    ports:
      - "8080:8080"
    depends_on:
      - "db"
      - "redis"
    environment:
      MYSQL_HOST: mysql_container
      REDIS_HOST: redis_container
      SRC_ROOT: /usr/src/app/server/
  db:
    image: mysql:8.0
    container_name: mysql_container
    volumes:
      - db-store:/var/lib/mysql
      - ./DB/logs:/var/log/mysql
      - ./DB/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=index-indicators
      - MYSQL_USER=index_indicators
      - MYSQL_PASSWORD=index_indicators
      - MYSQL_ROOT_PASSWORD=index_indicators
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
  redis:
    image: "redis:6.0-alpine"
    container_name: redis_container
    volumes:
      - "./server/redis:/redis"
    ports:
      - "6379:6379"
volumes:
  db-store:
